export enum OrderStatus {
    PENDING = "PENDING",
    ACCEPTED= "ACCEPTED",
    PREPARED= "PREPARED",
    ON_DELIVERY= "ON_DELIVERY",
    DELIVERED= "DELIVERED",
    CANCELLED= "CANCELLED",
    REJECTED= "REJECTED"
}